import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'butter-ghee', name: 'Butter & Ghee' },
  { id: 'yoghurt', name: 'Yoghurt' },
  { id: 'ice-cream', name: 'Ice Cream' },
  { id: 'milk', name: 'Liquid & Sterilized Milk' },
  { id: 'milk-powder', name: 'Milk Powder' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Pelwatte Salted Butter',
    description: 'Creamy, rich, and perfectly salted butter.',
    longDescription: 'Made from the freshest milk from local Sri Lankan farms, Pelwatte Salted Butter offers a rich, creamy texture and a perfectly balanced salty flavor. Ideal for spreading, baking, and cooking, it brings a touch of luxury to any dish.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'butter spread',
    categoryId: 'butter-ghee',
    nutritionalFacts: [
      { name: 'Energy', value: '717 kcal' },
      { name: 'Fat', value: '81g' },
      { name: 'Carbohydrates', value: '0.1g' },
      { name: 'Protein', value: '0.9g' },
    ],
  },
  {
    id: '2',
    name: 'Pelwatte Ghee',
    description: 'Pure and aromatic clarified butter.',
    longDescription: 'Our Pelwatte Ghee is a premium clarified butter, known for its rich aroma, nutty flavor, and high smoke point. It\'s a versatile cooking medium that is perfect for traditional recipes, frying, and as a flavorful topping.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'ghee jar',
    categoryId: 'butter-ghee',
    nutritionalFacts: [
      { name: 'Energy', value: '897 kcal' },
      { name: 'Fat', value: '99.7g' },
      { name: 'Carbohydrates', value: '0g' },
      { name: 'Protein', value: '0g' },
    ],
  },
  {
    id: '3',
    name: 'Pelwatte Drinking Yoghurt',
    description: 'A refreshing and healthy yoghurt drink.',
    longDescription: 'Enjoy the tangy and refreshing taste of Pelwatte Drinking Yoghurt. Packed with probiotics and made with real fruit flavors, it\'s a healthy and convenient snack for any time of the day.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'yoghurt drink',
    categoryId: 'yoghurt',
    nutritionalFacts: [
      { name: 'Energy', value: '78 kcal' },
      { name: 'Fat', value: '1.5g' },
      { name: 'Carbohydrates', value: '12g' },
      { name: 'Protein', value: '3.5g' },
    ],
  },
  {
    id: '4',
    name: 'Vanilla Ice Cream',
    description: 'Classic, creamy vanilla ice cream tub.',
    longDescription: 'Indulge in the timeless flavor of our classic Vanilla Ice Cream. Made with real vanilla extract and fresh cream, its smooth, rich texture makes it a perfect dessert for any occasion.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'vanilla icecream',
    categoryId: 'ice-cream',
    nutritionalFacts: [
      { name: 'Energy', value: '207 kcal' },
      { name: 'Fat', value: '11g' },
      { name: 'Carbohydrates', value: '24g' },
      { name: 'Protein', value: '3.5g' },
    ],
  },
  {
    id: '5',
    name: 'Chocolate Ice Cream',
    description: 'Rich and decadent chocolate ice cream.',
    longDescription: 'For the ultimate chocolate lover, our Chocolate Ice Cream is a dream come true. Made with rich cocoa and creamy dairy, every spoonful is a decadent and satisfying experience.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'chocolate icecream',
    categoryId: 'ice-cream',
    nutritionalFacts: [
      { name: 'Energy', value: '216 kcal' },
      { name: 'Fat', value: '12g' },
      { name: 'Carbohydrates', value: '25g' },
      { name: 'Protein', value: '4g' },
    ],
  },
  {
    id: '6',
    name: 'Pelwatte Full Cream Milk',
    description: 'Fresh and nutritious full cream UHT milk.',
    longDescription: 'Pelwatte Full Cream Milk is pure, fresh, and full of natural goodness. Sourced from our trusted local farms, it is perfect for drinking, with cereals, or in your favorite recipes.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'milk carton',
    categoryId: 'milk',
    nutritionalFacts: [
      { name: 'Energy', value: '60 kcal' },
      { name: 'Fat', value: '3.3g' },
      { name: 'Carbohydrates', value: '4.7g' },
      { name: 'Protein', value: '3.2g' },
    ],
  },
  {
    id: '7',
    name: 'Pelwatte Full Cream Milk Powder',
    description: 'Rich and creamy milk powder for all your needs.',
    longDescription: 'A household essential, Pelwatte Full Cream Milk Powder is made from 100% fresh milk. Its rich and creamy taste makes it ideal for beverages, cooking, and baking, providing nutrition and flavor in every scoop.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'milk powder',
    categoryId: 'milk-powder',
    nutritionalFacts: [
      { name: 'Energy', value: '496 kcal' },
      { name: 'Fat', value: '26g' },
      { name: 'Carbohydrates', value: '38g' },
      { name: 'Protein', value: '26g' },
    ],
  },
  {
    id: '8',
    name: 'Fruit Yoghurt Cup',
    description: 'Creamy yoghurt with real fruit pieces.',
    longDescription: 'Experience the perfect blend of creamy yoghurt and delicious real fruit. Our Fruit Yoghurt Cups are a wholesome and delightful snack, available in a variety of fruit flavors.',
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'fruit yoghurt',
    categoryId: 'yoghurt',
    nutritionalFacts: [
      { name: 'Energy', value: '98 kcal' },
      { name: 'Fat', value: '2.5g' },
      { name: 'Carbohydrates', value: '15g' },
      { name: 'Protein', value: '3.8g' },
    ],
  },
];

export const newsArticles = [
  {
    id: '1',
    title: 'Pelwatte Dairy Expands its Product Line',
    date: '2024-07-15',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'dairy products',
    summary: 'We are excited to announce the launch of our new range of artisanal cheeses, crafted with the same dedication to quality and freshness you expect from Pelwatte.',
  },
  {
    id: '2',
    title: 'Sustainability Initiatives at Pelwatte Farms',
    date: '2024-06-28',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'green farming',
    summary: 'Learn about our commitment to sustainable farming practices, including water conservation and renewable energy, to protect our beautiful Sri Lankan environment.',
  },
  {
    id: '3',
    title: 'Pelwatte Awarded "Best Dairy Provider 2024"',
    date: '2024-05-10',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'award trophy',
    summary: 'We are honored to be recognized for our excellence in dairy production. This award is a testament to the hard work of our farmers and employees.',
  },
];
